### PR TITLE
Adding logging and fixing job error tag

### LINKED ISSUE #13: log a queue event when a job is called
I think the best way to handle this is to just put an anon function in the define and have the first thing be the log call and then call the method here: https://github.com/firstandthird/hapi-agenda/blob/master/index.js#L51

### LINKED ISSUE #14: fix tag for failed job
https://github.com/firstandthird/hapi-agenda/blob/master/index.js#L27 should be 'error' instead of complete

### PR DESCRIPTION
**Pull request by ecwillis**
Closes #13 
Closes #14

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -48,7 +48,10 @@ exports.register = function(plugin, options, next) {
       opts = value;
     }
 
-    agenda.define(name, opts, method.bind(plugin));
+    agenda.define(name, opts, function(data, done) {
+      plugin.log(['agenda', 'processing'], { opts: opts });
```
Comment (jgallen23) [inline index.js]: lets rename processing to 'queue'

**Comment by ecwillis** [comment]
Done.
